config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get '/users/show/:id', to: 'users#show', as: 'show_user'
  get '/users/edit/:id', to: 'users#edit', as: 'user'
  patch '/users/edit/:id', to: 'users#update', as: 'update_user'


  devise_for :users
  resources :tweets do 
    resources :comments
    end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "tweets#index"

  get '/tweet/:id/like', to: 'tweets#like', as: 'like'
  get '/tweet/:id/unlike', to: 'tweets#unlike', as: 'unlike'
  get '/tweets/:tweet_id/comments/:id', to: 'comments#destroy', as: 'delete_comment'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet

    validates :user_id, uniqueness: { scope: :tweet_id }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :comments, dependent: :destroy

    validates :body, length: {minimum: 5, maximum: 250}, presence: true

    def liked?(user)
        # likes.where(user_id: user.id, tweet_id: tweet.id).exists?
        self.likes.where(user_id: user.id).exists?
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_tweet, only: %i[ create edit update destroy]


  # GET /comments or /comments.json
 

  # GET /comments/1 or /comments/1.json
  

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @tweet.comments.build(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to root_path, notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to root_path, notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.permit(:text, :user_id)
    end

    def set_tweet
      @tweet = Tweet.find(params[:tweet_id])
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy like unlike]
  before_action :authenticate_user!
  # GET /tweets or /tweets.json
  def index
    # @tweets = current_user.tweets
    @tweets = Tweet.all.order(created_at: :DESC)
    @tweet = current_user.tweets.new 
    @user = User.find(@tweet.user_id)
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = current_user.tweets.build(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to root_path, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  # Add like to a tweet 
  def like
    @like = @tweet.likes.build({user_id: current_user.id})

    if @like.save
      redirect_to root_path
    else
      redirect_to tweets_url, alert: @like.errors
    end
  end

  def unlike
    @like = @tweet.likes.find_by(user_id: current_user.id)

    @like.destroy

    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:body, :owner_id)
    end

    def like_params
      params.permit(:id)
    end

    def check_owner
      if current_user.id != @tweet.user_id
        respond_to do |format|
          format.html { redirect_to root_path, alert: "Login as tweet owner to edit it." }
          format.json { head :no_content }
        end 
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[ show edit update ]
  def index
    @users = User.all
  end

  def show

  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to show_user_path(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :email, :phone, :address, :talk, :relation, :netflix, :games, :adventure, :job)
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Typeshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> 
  </head>

  <body>
  <script>
  function showComments(id){
    
    if ($("#tweet"+id).hasClass("comments-section-none")){
        $("#tweet"+id).removeClass("comments-section-none")
        $("#tweet"+id).addClass("comments-section-visible")
    }else{
        $("#tweet"+id).removeClass("comments-section-visible")
        $("#tweet"+id).addClass("comments-section-none")
    }
}
  </script>
    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success" role="alert"> <%= msg %> </div>
      <% else %>
        <div class="alert alert-danger" role="alert"> <%= msg %> </div>
      <% end %>
    <% end %>
    <%# nav bar %>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href=<%= root_path%>>TypeShare</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
            <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= current_user.full_name unless !user_signed_in?%>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="<%= show_user_path(current_user) %>">Profile</a></li>
                <li><a class="dropdown-item" href="#">Friends</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :get }, class: "dropdown-item" %></li>
              </ul>
            </li>
              <% else %>
              <a class="nav-link active" aria-current="page" href=<%= new_user_session_path %>>log in</a>
              <% end %>
            </li>
            
          </ul>
        </div>
      </div>
    </nav>
    <%# end navbar %>
    <div class="row">
  
      <div class="container col-md-9 col-lg-5 col-sm-9 background-second-color rounded p-5">
        <%= yield %>
      </div>

      <div class=" col-md-2 col-lg-2 col-sm-2 friends px-5">
      <% if user_signed_in? %>
        <h5 class="float-right">Contacts</h5>
        <hr>
      <% end %>
        <% if user_signed_in? %>
          <% @user_list = User.all %>
          <% @user_list.map do |user| %>
            <% if user != current_user %>
            <div class="d-flex flex-start my-3 friend p-2 rounded">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(26).webp" alt="avatar" width="40"
                height="40" />
                <a href="/users/show/<%= user.id %>"><div class="pt-2 friend-name text-truncate"><%= user.full_name.blank? ? user.email : user.full_name %></a></div>
            </div>
            <% end %>
          <% end %>
        <% end %>
        
      </div>
  
    </div>
  
  </body>
</html>

app/views/tweets/_comment.html.erb
<div class="card-body px-5 mb-2 border rounded">
  <div class="d-flex flex-start align-items-center">
      <img class="rounded-circle shadow-1-strong me-3"
        src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="60"
        height="60" />
      <div>
        <h6 class="fw-bold text-primary mb-1"><a href="/users/show/<%= comment.user_id %>"><%= User.find(comment.user_id).full_name.blank? ? User.find(comment.user_id).email : User.find(comment.user_id).full_name %></a></h6>
        <p class="text-muted small mb-0">
          Shared publicly - <%= comment.created_at.strftime("%A %H:%M") %>
        </p>
      </div>
    </div>

    <p class="mt-3 mb-4 pb-2 text-black">
      <%= comment.text %>
    </p>
    <% if comment.user_id == current_user.id %>
      <div><%= button_to image_tag("trash.svg"), delete_comment_path(comment.tweet_id, comment.id), method: :delete, class: "btn btn-light border-none" %></div>
    <% end %>
  </div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
  <% if !current_user.full_name.blank? %>
  <%= form.text_area :body, placeholder: "Hi "+current_user.full_name.split(" ").first+"! What's up?",
     style: "width: 100%; height: 10em", class: "p-3 rounded", id: "tweet_textarea" %>
  
  <% else %>
  <%= form.text_area :body, placeholder: "Hi "+current_user.email+"! What's up?",
     style: "width: 100%; height: 10em", class: "p-3 rounded", id: "tweet_textarea" %>
  
  <% end %>
    </div>

  <div class="d-flex justify-content-end mt-3">
    <%= form.submit "Share", class: "btn btn-primary"%>
  </div>
  <hr>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">

  <section class="mb-2">
    <div class="row d-flex justify-content-center ">
      <div class="col-md-12 col-lg-12 col-xl-12">
        <div class="card background-base-color">
          <div class="card-body">
            <div class="d-flex flex-start align-items-center">
              <img class="rounded-circle shadow-1-strong me-3"
                src="https://mdbcdn.b-cdn.net/img/Photos/Avatars/img%20(19).webp" alt="avatar" width="60"
                height="60" />
              <div>
                <h6 class="fw-bold text-primary mb-1"><a href="/users/show/<%= tweet.user_id %>"><%= User.find(tweet.user_id).full_name.blank? ? User.find(tweet.user_id).email : User.find(tweet.user_id).full_name%></a></h6>
                <p class="text-muted small mb-0">
                  Shared publicly - <%= tweet.created_at.strftime("%A %H:%M")%>
                </p>
              </div>
              <% if current_user.id == tweet.user_id %>
              <div style="margin-left: auto">
                  <%= link_to tweet_path(tweet), method: "get", class: "icon-zoom" do %> 
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                      <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                      <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                    </svg>
                  <% end %>
              </div>
              <% end %>
            </div>

            <p class="mt-3 mb-4 pb-2">
              <%= tweet.body %>
            </p>

            <div class="small d-flex justify-content-end">
              <div class="d-flex align-items-center me-3 gap-2">
                
                <% if tweet.liked?(current_user) %>
                  <div>
                    <%= tweet.likes.blank? ? 0 : tweet.likes.count %>
                  </div>
                  <%= link_to unlike_path(tweet), method: "get", class: "heart-hover icon-zoom" do %> 
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-heart-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"/>
                    </svg>
                  <% end %>
                  <% else %>
                    <div>
                      <%= tweet.likes.blank? ? 0 : tweet.likes.count %>
                    </div>

                    <%= link_to like_path(tweet), method: "get", class: "heart-hover icon-zoom" do %> 
                      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="red" class="bi bi-heart" viewBox="0 0 16 16">
                      <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053c-.523 1.023-.641 2.5.314 4.385.92 1.815 2.834 3.989 6.286 6.357 3.452-2.368 5.365-4.542 6.286-6.357.955-1.886.838-3.362.314-4.385C13.486.878 10.4.28 8.717 2.01L8 2.748zM8 15C-7.333 4.868 3.279-3.04 7.824 1.143c.06.055.119.112.176.171a3.12 3.12 0 0 1 .176-.17C12.72-3.042 23.333 4.867 8 15z"/>
                      </svg>
                    <% end %>
                <% end %>

              </div>
              <div class="d-flex align-items-center me-3 gap-2">
                <div>
                <%= tweet.comments.blank? ? 0 : tweet.comments.count %>
                </div>
                <div class="comment-toggler icon-zoom" onclick="showComments(<%= tweet.id %>)">
                  <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-chat" viewBox="0 0 16 16">
                  <path d="M2.678 11.894a1 1 0 0 1 .287.801 10.97 10.97 0 0 1-.398 2c1.395-.323 2.247-.697 2.634-.893a1 1 0 0 1 .71-.074A8.06 8.06 0 0 0 8 14c3.996 0 7-2.807 7-6 0-3.192-3.004-6-7-6S1 4.808 1 8c0 1.468.617 2.83 1.678 3.894zm-.493 3.905a21.682 21.682 0 0 1-.713.129c-.2.032-.352-.176-.273-.362a9.68 9.68 0 0 0 .244-.637l.003-.01c.248-.72.45-1.548.524-2.319C.743 11.37 0 9.76 0 8c0-3.866 3.582-7 8-7s8 3.134 8 7-3.582 7-8 7a9.06 9.06 0 0 1-2.347-.306c-.52.263-1.639.742-3.468 1.105z"/>
                  </svg>
                </div>

              </div>

            </div>
          </div>
          <div class="card-footer py-3 border-0 comments-section-none " id="tweet<%= tweet.id %>" style="background-color: #f8f9fa;">
            <div class="comment-textarea mt-3">
              <%= form_with url: "/tweets/"+tweet.id.to_s+"/comments", method: :post do |form| %>
              <%= form.text_area :text, placeholder: "Make a comment", class: "form-control mb-3" %>
              <%= form.hidden_field :user_id, value: current_user.id %>
              <div class="d-flex flex-row-reverse"><%= form.submit "post", class: "btn btn-secondary mb-3" %></div>
              <% end %>
              </div>
              <div class="comment-body">
              <% tweet.comments.map do |comment| %>
              <%= render "comment", comment: comment%>
              <% end %>
            </div>
          </div>

          

        </div>
      </div>
    </div>
</section>
</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<%= render "form", tweet: @tweet %>


<div id="tweets" class="mt-5">
  <% @tweets.each do |tweet| %>
      <div class="tweet-container rounded">
        <%= render tweet %>
      </div>
    <% end %>  
</div>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>

app/views/users/edit.html.erb
<section style="background-color: #eee;" class="rounded">
<%= form_with model: @user do |f| %>
<div class="container py-5 rounded">

    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <p class="text-muted mt-3 mb-1"><%= @user.job %></p>
            <p class="text-muted mb-4"><%= @user.full_name%></p>
            <div class="d-flex justify-content-center mb-2">
              <button type="button" class="btn btn-primary">Follow</button>
            </div>
          </div>
        </div>
        <div class="card mb-4 mb-lg-0">
          <div class="card-body p-0">
            <ul class="list-group list-group-flush rounded-3">
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fas fa-globe fa-lg text-warning"></i>
                <p class="mb-0">https://mdbootstrap.com</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-github fa-lg" style="color: #333333;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-twitter fa-lg" style="color: #55acee;"></i>
                <p class="mb-0">@mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-instagram fa-lg" style="color: #ac2bac;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;"></i>
                <p class="mb-0">mdbootstrap</p>
              </li>
            </ul>
          </div>
        </div>
      </div>
     <div class="col-lg-8 text-black">
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Full Name</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= f.text_field :full_name, placeholder: @user.full_name, class: "form-control form-control-sm"%></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Email</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= f.email_field :email, placeholder: @user.email, class: "form-control form-control-sm"%></p>
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Phone</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= f.text_field :phone, placeholder: @user.phone, class: "form-control form-control-sm"%></p>
              </div>
            </div>
            <hr>
            
            <div class="row">
              <div class="col-sm-3">
                <p class="mb-0">Address</p>
              </div>
              <div class="col-sm-9">
                <p class="text-muted mb-0"><%= f.text_field :address, placeholder: @user.address, class: "form-control form-control-sm"%></p>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <div class="card mb-4 mb-md-0">
              <div class="card-body">
                <p class="mb-4"><span class="text-primary font-italic me-1">About</span>
                </p>
                <p class="mb-1" style="font-size: .77rem;">Like to talk</p>
                <%= f.number_field :talk, in: 0..100, step: 1, placeholder: @user.talk, class: "form-control form-control-sm"%>
                <p class="mt-4 mb-1" style="font-size: .77rem;">Ready for relationship</p>
                <%= f.number_field :relation, in: 0..100, step: 1, placeholder: @user.relation, class: "form-control form-control-sm"%>

                <p class="mt-4 mb-1" style="font-size: .77rem;">Netflix lover</p>
                <%= f.number_field :netflix, in: 0..100, step: 1, placeholder: @user.netflix, class: "form-control form-control-sm"%>

                <p class="mt-4 mb-1" style="font-size: .77rem;">Video Games</p>
                <%= f.number_field :games, in: 0..100, step: 1, placeholder: @user.games, class: "form-control form-control-sm"%>

                <p class="mt-4 mb-1" style="font-size: .77rem;">Adventurer</p>
                <%= f.number_field :adventure, in: 0..100, step: 1, placeholder: @user.adventure, class: "form-control form-control-sm"%>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
  </div>
  <%= f.submit class: "btn btn-primary m-3"%>
<% end%>
</section>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>